[package]
name = "bcad-io"
version = "0.1.0"
edition = "2021"

[dependencies]
bcad-kernel = { path = "../bcad-kernel" }
serde.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
thiserror.workspace = true
dxf.workspace = true
gltf.workspace = true
zip.workspace = true
truck-stepio.workspace = true
truck-modeling.workspace = true
truck-topology = { workspace = true }
